# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/conno/RAT2/RAT2.cache/wt [current_project]
set_property parent.project_path C:/Users/conno/RAT2/RAT2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/conno/RAT2/RAT2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  {C:/Users/conno/RAT2/RAT Files/Test1C.mem}
  {C:/Users/conno/RAT2/RAT Files/Test7a.mem}
  {C:/Users/conno/RAT2/RAT Files/Test6a.mem}
  {C:/Users/conno/RAT2/RAT Files/Test3a.mem}
  {C:/Users/conno/RAT2/RAT Files/Test1.mem}
  {C:/Users/conno/RAT2/RAT Files/Test1B.mem}
  {C:/Users/conno/RAT2/RAT Files/TESTALL.mem}
  {C:/Users/conno/RAT2/RAT Files/Test5A.mem}
  {C:/Users/conno/RAT2/RAT Files/Test4B.mem}
  {C:/Users/conno/RAT2/RAT Files/Test6B.mem}
  {C:/Users/conno/RAT2/RAT Files/Test2A.mem}
  {C:/Users/conno/RAT2/RAT Files/Test3B.mem}
  {C:/Users/conno/RAT2/RAT Files/Test4A.mem}
  {C:/Users/conno/RAT2/RAT Files/PHASE3.mem}
  {C:/Users/conno/RAT2/RAT Files/VGA Files/drawdot_80_60.mem}
  {C:/Users/conno/RAT2/RAT Files/Final Project RAT Code Files/Final_Project.mem}
  {C:/Users/conno/RAT2/RAT Files/Keyboard_sv/KeyboardTest.mem}
}
read_verilog -library xil_defaultlib -sv {
  {C:/Users/conno/RAT2/RAT Files/BCD.sv}
  {C:/Users/conno/RAT2/RAT Files/CathodeDriver.sv}
  {C:/Users/conno/RAT2/RAT Files/SevSegDisp.sv}
  {C:/Users/conno/RAT2/RAT Files/ALU.sv}
  {C:/Users/conno/RAT2/RAT Files/ControlUnit_Template.sv}
  {C:/Users/conno/RAT2/RAT Files/FLAGS.sv}
  {C:/Users/conno/RAT2/RAT Files/MUX.sv}
  {C:/Users/conno/RAT2/RAT Files/ProgCounter.sv}
  {C:/Users/conno/RAT2/RAT Files/ProgROM.sv}
  {C:/Users/conno/RAT2/RAT Files/RATMCU.sv}
  {C:/Users/conno/RAT2/RAT Files/RegFile.sv}
  {C:/Users/conno/RAT2/RAT Files/ScrRam.sv}
  C:/Users/conno/RAT2/RAT2.srcs/sources_1/new/Stack_Pointer.sv
  C:/Users/conno/RAT2/RAT2.srcs/sources_1/new/InterruptReg.sv
  {C:/Users/conno/RAT2/RAT Files/VGA Files/vga_fb_driver.sv}
  {C:/Users/conno/RAT2/RAT Files/VGA Files/ram8k_8.sv}
  {C:/Users/conno/RAT2/RAT Files/VGA Files/vga_driver.sv}
  {C:/Users/conno/RAT2/RAT Files/VGA Files/RAT_WRAPPER.sv}
  {C:/Users/conno/RAT2/RAT Files/Keyboard_sv/KeyboardDriver.sv}
  {C:/Users/conno/RAT2/RAT Files/RandomGenerator/RandGen.sv}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/conno/RAT2/RAT Files/VGA Files/VGA_Constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/conno/RAT2/RAT Files/VGA Files/VGA_Constraints.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top RAT_WRAPPER -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RAT_WRAPPER.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RAT_WRAPPER_utilization_synth.rpt -pb RAT_WRAPPER_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
